### ISSUE TITLE
Illuminate Windows documentation table missing header

### ISSUE THREAD

**Issue by miwent** [Graylog2/illuminate-documentation#43]
The documentation for the Illuminate pack for Windows includes a table which has an incorrect header.

![image](https://github.com/user-attachments/assets/d752b7d2-351c-413b-a639-e4cf6607f371)

The header in this image should instead be a table entry. The header should be "Field Name" and "Field Description".

**Comment by annie-zempel** [comment]
@miwent Fixed on all branches.
